---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons-of-addons
  namespace: argocd
  labels:
    app.kubernetes.io/name: addons
    app.kubernetes.io/managed-by: argocd
spec:
  description: Cluster addons
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-of-addons
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
  labels:
    app.kubernetes.io/name: addons
    app.kubernetes.io/managed-by: argocd
spec:
  project: addons-of-addons
  source:
    repoURL: https://github.com/estudosdevops/homelab.git
    targetRevision: refactor/homelab
    path: kubernetes/addons/manager
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
