global:
  domain: homelab.tech
  argoNamespace: argocd
  storageClass: longhorn
  project: homelab  # Projeto padrão para todas as apps

  # Configurações de TLS e certificados
  tls:
    secretName: wildcard-tls
    clusterIssuer: homelab-ca-issuer

# Criar o projeto automaticamente
createProject: true

enabledAddons:
  - cert-manager
  - metallb
  - ingress-nginx
  - longhorn
  - vault
  - external-secrets
  - pihole
  - kube-prometheus-stack
  - loki
