---
- name: DHCP | Create pools
  community.routeros.api_modify:
    path: ip pool
    data:
      - name: "{{ item.key }}"
        ranges: "{{ item.value.dhcp.pool_start }}-{{ item.value.dhcp.pool_end }}"
  loop: "{{ mikrotik_networks | dict2items }}"
  when: item.value.dhcp.enabled | default(false)

- name: DHCP | Configure networks
  community.routeros.api_modify:
    path: ip dhcp-server network
    data:
      - address: "{{ item.value.network }}"
        gateway: "{{ item.value.gateway | ansible.utils.ipaddr('address') }}"
        dns-server: "{{ item.value.dhcp.dns }}"
        comment: "{{ item.key }}"
  loop: "{{ mikrotik_networks | dict2items }}"
  when: item.value.dhcp.enabled | default(false)

- name: DHCP | Create servers
  community.routeros.api_modify:
    path: ip dhcp-server
    data:
      - name: "{{ item.key }}"
        interface: "{{ item.value.bridge }}"
        address-pool: "{{ item.key }}"
        disabled: "no"
  loop: "{{ mikrotik_networks | dict2items }}"
  when: item.value.dhcp.enabled | default(false)
