---
- name: Firewall | reset dynamic HOME-to-homelab allow list
  ansible.builtin.set_fact:
    _mikrotik_fw_homelab_allows: []

- name: Firewall | build per-host HOME-to-homelab allow rules
  ansible.builtin.set_fact:
    _mikrotik_fw_homelab_allows: "{{ _mikrotik_fw_homelab_allows + [_rule] }}"
  vars:
    _rule:
      chain: forward
      src-address: "{{ item }}"
      dst-address: "{{ mikrotik_networks.homelab.network }}"
      action: accept
      comment: "ansible:forward home {{ item }} to homelab"
  loop: "{{ mikrotik_homelab_allowed_hosts }}"

- name: Firewall | ensure input chain
  community.routeros.api_modify:
    path: ip firewall filter
    restrict:
      - field: chain
        values:
          - input
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    ensure_order: true
    data: "{{ mikrotik_firewall_input }}"

- name: Firewall | ensure forward chain
  community.routeros.api_modify:
    path: ip firewall filter
    restrict:
      - field: chain
        values:
          - forward
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    ensure_order: true
    data: "{{ mikrotik_firewall_forward_before_host_allows + mikrotik_firewall_forward_homelab_services + _mikrotik_fw_homelab_allows + mikrotik_firewall_forward_after_host_allows }}"
