---
- name: INTERFACES | Configure gateway addresses
  community.routeros.api_modify:
    path: ip address
    data:
      - address: "{{ item.value.gateway }}"
        interface: "{{ item.value.bridge }}"
        comment: "{{ item.key }}"
  loop: "{{ mikrotik_networks | dict2items }}"
