---
- name: Configure NAT masquerade
  community.routeros.api_modify:
    path: ip firewall nat
    data:
      - chain: srcnat
        out-interface: "{{ mikrotik_pppoe.name }}"
        action: masquerade
        comment: "NAT to Internet"
