apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "alloy"
  namespace: argocd
  labels:
    app.kubernetes.io/name: "alloy"
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: addons
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: "alloy-{{ .name }}"
      labels:
        app.kubernetes.io/name: "alloy"
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: addons
    spec:
      project: addons
      destination:
        server: "{{ .server }}"
        namespace: "alloy"
      source:
        repoURL: https://github.com/estudosdevops/homelab.git
        targetRevision: feat/ansible-role-observability
        path: "kubernetes/addons/alloy"
        helm:
          releaseName: "alloy"
          valueFiles:
            - values/common.yaml
            - "values/{{ .name }}.yaml"
          ignoreMissingValueFiles: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
  templatePatch: |
    metadata:
      name: "alloy-{{ .name }}"
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
