# addons/vault/values.yaml
metadata:
  annotations:
    app.kubernetes.io/description: "HashiCorp Vault para secrets management"

# Project específico (opcional, se não definir usa o global)
project: vault

chart:
  repository: https://helm.releases.hashicorp.com
  name: vault
  version: "0.30.1"

destination:
  namespace: vault

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

helm:
  values:
    injector:
      enabled: false
    global:
      enabled: true
      tlsDisable: true

    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "{{ .Values.global.tls.clusterIssuer }}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        hosts:
          - host: "vault.{{ .Values.global.domain }}"
        tls:
          - secretName: "{{ .Values.global.tls.secretName }}"
            hosts:
              - "vault.{{ .Values.global.domain }}"

      dataStorage:
        size: 1Gi
        storageClass: "{{ .Values.global.storageClass }}"

      standalone:
        enabled: true
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "file" {
            path = "/vault/data"
          }

    ui:
      enabled: true
      serviceType: "ClusterIP"
