---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  tags:
    - all
    - setup
    - always

- name: Install common packages
  package:
    name:
      - vim
      - htop
      - git
      - curl
      - wget
    state: present
  tags:
    - all
    - setup
    - always

- name: Adjust kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - {name: "fs.inotify.max_queued_events", value: 16384}
    - {name: "fs.inotify.max_user_instances", value: 8192}
    - {name: "fs.inotify.max_user_watches", value: 524288}
  tags:
    - all
    - setup
    - always

- name: Configure timezone
  timezone:
    name: America/Sao_Paulo
  tags:
    - all
    - setup
    - always
