installCRDs: true

crds:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true

replicaCount: 1

serviceMonitor:
  enabled: false

webhook:
  logLevel: info

certController:
  logLevel: info
