---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gha-runner-scale
  namespace: gha-runner-scale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gha-runner-scale
  data:
    - secretKey: github-token
      remoteRef:
        key: prod/shared
        property: github-token
