---
bases:
  - "../../bases/helmDefaults.yaml"

environments:
  homelab:
    kubeContext: default
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: metallb
    namespace: metallb-system
    chart: bitnami/metallb
    version: ~6.4.10
    installed: true
    labels:
      tier: metallb
    hooks:
      - events:
          - postsync
        showlogs: true
        command: kubectl apply -f ./manifests/ip-address-pool.yml
    values:
      - values/values.yaml.gotmpl
      # - values/{{ .Environment.Name }}.yaml.gotmpl
    disableValidationOnInstall: true