---
bases:
  - "../../bases/helmDefaults.yaml"

---
repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: ~0.14.9
    installed: true
    labels:
      tier: metallb
    hooks:
      - events:
          - postsync
        showlogs: true
        command: kubectl apply -f ./addons/releases/metallb/manifests/ip-address-pool.yml
    values:
      - values/values.yaml.gotmpl
    disableValidationOnInstall: true
