---
bases:
  - "../../bases/helmDefaults.yaml"

---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

---
releases:
  - name: kube-prometheus-stack
    namespace: monitoring-system
    chart: prometheus-community/kube-prometheus-stack
    version: ~73.2.0
    values:
      - values/values.yaml.gotmpl
    labels:
      tier: monitoring
    disableValidationOnInstall: true
