---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubechecks-secret
  namespace: kubechecks
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: kubechecks-secret
  data:
    - secretKey: KUBECHECKS_VCS_TOKEN
      remoteRef:
        key: prod/shared
        property: github-token
    - secretKey: KUBECHECKS_ARGOCD_API_TOKEN
      remoteRef:
        key: prod/shared
        property: argocd-token
