---
- name: Configure Grafana repository
  ansible.builtin.import_tasks: grafana_repo.yml

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Create provisioning directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: grafana
    mode: "0755"
  loop:
    - /etc/grafana/provisioning
    - /etc/grafana/provisioning/datasources
    - /etc/grafana/provisioning/dashboards

- name: Configure Grafana
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ grafana.templates }}"
  loop_control:
    label: "{{ item.dest }}"
  notify: Restart Grafana

- name: Enable Grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
