---
bases:
  - "../../bases/helmDefaults.yaml"

---
repositories:
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/

releases:
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: ~2.30.0
    installed: true
    labels:
      tier: dns
    values:
      - values/values.yaml.gotmpl
    disableValidationOnInstall: true
