---
apiVersion: v2
name: eexternal-secrets
description: Um chart wrapper para instalar external-secrets.
type: application
version: 0.1.0

dependencies:
  - name: external-secrets
    version: 0.*.*
    repository: https://charts.external-secrets.io/
