# addons/external-secrets/values.yaml
metadata:
  annotations:
    app.kubernetes.io/description: "External Secrets Operator para integração com Vault"
    argocd.argoproj.io/sync-wave: "1"

# Project específico (opcional, se não definir usa o global)
project: external-secrets

chart:
  repository: https://charts.external-secrets.io
  name: external-secrets
  version: "0.19.2"

destination:
  namespace: external-secrets

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

helm:
  values:
    installCRDs: true
    replicaCount: 1

    serviceMonitor:
      enabled: false

    controller:
      logLevel: info

    webhook:
      logLevel: info

    certController:
      logLevel: info

    # Configuração específica para ClusterSecretStore
    externalSecrets:
      enabled: true
      vault:
        server: "http://vault.vault.svc.cluster.local:8200"
        token: ""  # ⚠️ Configurar com token real para DEV/TESTE (não commitar)
      environments:
        - name: stg
          path: "stg"
        - name: sdx
          path: "sdx"
        - name: prod
          path: "prod"
