---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ceph-csi-rbd-secret
  data:
    - secretKey: userID
      remoteRef:
        key: prod/addons/ceph-csi
        property: userID
    - secretKey: userKey
      remoteRef:
        key: prod/addons/ceph-csi
        property: userKey
