---
bases:
  - "../../bases/helmDefaults.yaml"

---
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: ~8.1.0
    installed: true
    labels:
      tier: deploy
    values:
      - values/values.yaml.gotmpl
    disableValidationOnInstall: true

  - name: argo-rollouts
    namespace: argo-rollouts
    chart: argo/argo-rollouts
    version: ~2.39.0
    installed: true
    labels:
      tier: rollouts
    values:
      - values/rollouts.yaml.gotmpl
    disableValidationOnInstall: true
