beyla:
  config:
    data:
      otel_metrics_export:
        endpoint: "http://grafana-alloy.grafana-alloy.svc.cluster.local:4317"

      otel_traces_export:
        endpoint: "http://grafana-alloy.grafana-alloy.svc.cluster.local:4317"

      attributes:
        kubernetes:
          enable: true
          cluster_name: "homelab"

      discovery:
        instrument:
          - open_ports: 8080

  env:
    BEYLA_EBPF_BTF_PATH: "/sys/kernel/btf/vmlinux"

  securityContext:
    privileged: true

  tolerations:
    - effect: NoSchedule
      operator: Exists
