---
beyla:
  config:
    data:
      ebpf:
        track_processes: false
        bpf_fs_path: "/sys/fs/bpf"

      otel_metrics_export:
        endpoint: "http://grafana-alloy.grafana-alloy.svc.cluster.local:4317"
      otel_traces_export:
        endpoint: "http://grafana-alloy.grafana-alloy.svc.cluster.local:4317"

      attributes:
        kubernetes:
          enable: true
          cluster_name: "homelab-prod"

      discovery:
        services:
          - name: sample-api
            open_ports: 8080
            # Opcional: filtrar por namespace específico se preferir
            # k8s_namespace: "default"

  volumeMounts:
    - name: sys-fs-bpf
      mountPath: /sys/fs/bpf
    - name: sys-kernel-debug
      mountPath: /sys/kernel/debug

  volumes:
    - name: sys-fs-bpf
      hostPath:
        path: /sys/fs/bpf
    - name: sys-kernel-debug
      hostPath:
        path: /sys/kernel/debug

  tolerations:
    - effect: NoSchedule
      operator: Exists
