---
all:
  vars:
    domain: homelab.tech
    ansible_ssh_private_key_file: "~/.ssh/id_rsa.pub"
raspberrypi:
  hosts:
    adguardhome:
      {
        ansible_host: 192.168.10.2,
        ansible_user: pi,
        ansible_become: true,
        ansible_password: "{{ adguardhome_ssh_password }}",
      }
mikrotik:
  hosts:
    rb-home:
      {
        ansible_host: 192.168.10.1,
        ansible_user: "{{ mikrotik_api_user }}",
        ansible_connection: local,
        ansible_password: "{{ mikrotik_api_password }}",
      }
vault:
  hosts:
    vault0: {
        ansible_host: 192.168.20.20,
        ansible_user: "ubuntu",
        # ansible_connection: local,
        #ansible_ssh_private_key_file: "~/.ssh/id_rsa.pub",
      }
proxmox:
  vars:
    ansible_user: root
    ansible_become: true
    ansible_password: "{{ proxmox_root_password }}"
  hosts:
    pve01:
      ansible_host: 192.168.20.2
    pve02:
      ansible_host: 192.168.20.3
    pve03:
      ansible_host: 192.168.20.4
    pve04:
      ansible_host: 192.168.20.5
