# Description: Install adguardhome Raspberry pi Zero 2w
---
- name: Install adguardhome on Raspberry
  hosts: raspberrypi
  gather_facts: true
  roles:
    - adguardhome
  vars:
    adguardhome_users:
      - username: admin
        password: "{{ adguardhome_admin_password }}"
