# Description: Install adguardhome Raspberry pi Zero 2w
---
- name: Install adguardhome on Raspberry
  hosts: raspberry
  gather_facts: true
  become: yes
  roles:
    - adguardhome
  vars:
    adguardhome_users:
      - username: admin
        password: 'encrypted'
