# Description: Create k3s cluster and install k8s addons
---
- name: Create Kubernetes cluster
  hosts: all
  roles:
    - setup
    - k3s
 
- name: Install k8s addons
  hosts: localhost
  roles:
    - cilium