---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: argocd
  labels:
    app.kubernetes.io/name: addons
    app.kubernetes.io/managed-by: argocd
spec:
  description: Cluster addons
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
