---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token-secret
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: github-token-secret
  data:
    - secretKey: github-token
      remoteRef:
        key: prod/shared
        property: github-token
