{{- if has "external-secrets" .Values.enabledAddons }}
{{- $addonValues := (.Files.Get "addons/external-secrets/values.yaml" | fromYaml) }}
{{- if $addonValues.helm.values.externalSecrets.enabled }}
# Secret para autenticação do vault
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
  labels:
    {{- include "homelab.labels" . | nindent 4 }}
type: Opaque
data:
  token: "{{ $addonValues.helm.values.externalSecrets.vault.token | b64enc }}"
---
# Loop para ClusterSecretStore por ambiente
{{- range $addonValues.helm.values.externalSecrets.environments }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-{{ .name }}
  labels:
    {{- include "homelab.labels" $ | nindent 4 }}
    homelab.tech/environment: {{ .name }}
    app.kubernetes.io/component: vault-backend
spec:
  provider:
    vault:
      server: "{{ $addonValues.helm.values.externalSecrets.vault.server }}"
      path: "{{ .path }}"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
---
{{- end }}
{{- end }}
{{- end }}
