bases:
  - "../../bases/helmDefaults.yaml"

---
repositories:
  - name: loki
    url: https://grafana.github.io/helm-charts

---
releases:
  - name: loki
    chart: grafana/loki
    namespace: monitoring-system
    version: '~6.30.1'
    values:
      - values/values.yaml.gotmpl
    labels:
      tier: monitoring
    disableValidationOnInstall: true