---
csiConfig:
  - clusterID: 655ea995-958e-4f71-80f1-6093ede327a1
    monitors:
      - 192.168.20.2:6789
      - 192.168.20.3:6789
      - 192.168.20.4:6789

csiDriver:
  name: rbd.csi.ceph.com
  attachRequired: true
  podInfoOnMount: false
  seLinuxMount: false

storageClass:
  create: true
  name: ceph-csi-rbd
  pool: rbd
  reclaimPolicy: Retain
  allowVolumeExpansion: true

nodeplugin:
  httpMetrics:
    enabled: false

provisioner:
  name: provisioner
  replicaCount: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  priorityClassName: system-cluster-critical
  timeout: 60s
  setmetadata: true
  httpMetrics:
    service:
      enabled: false
