---
bases:
  - "../bases/helmDefaults.yaml"
---
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: ~9.5.15
    installed: true
    labels:
      tier: deploy
    values:
      - values/values.yaml.gotmpl
    disableValidationOnInstall: true
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "values/addons.yaml"

  - name: argo-rollouts
    namespace: argo-rollouts
    chart: argo/argo-rollouts
    version: ~2.40.9
    installed: true
    labels:
      tier: rollouts
    needs:
      - argocd/argocd
    values:
      - values/rollouts.yaml.gotmpl
    disableValidationOnInstall: true
