manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - curl
  - wget
  - unzip
  - qemu-guest-agent

package_update: true
package_upgrade: true

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
