---
mikrotik_identity: "RB_HOME"

# Customize bridges according to your physical ports
mikrotik_bridges:
  - name: "home"
    ports:
      - ether2
      - ether3
      - ether4
  - name: "homelab"
    ports:
      - ether5

# PPPoE configuration (use vault for password)
mikrotik_pppoe:
  enabled: true
  interface: ether1
  name: "pppoe-vivo"
  user: "{{ mikrotik_pppoe_user }}"
  password: "{{ mikrotik_pppoe_password }}"
