base-app:
  nameOverride: "sample-api"
  pods:
    image:
      name: fcruzcoelho/sample-api
      tag: v0.2.0
      pullPolicy: IfNotPresent

    annotations:
      werf.io/show-service-messages: "true"

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
