apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    homelab.tech:53 {
      errors
      cache 30
      forward . 192.168.15.102
    }
