---
- name: Install required Python packages
  ansible.builtin.pip:
    name:
      - kubernetes
      - openshift
    state: present
  delegate_to: localhost
  run_once: true

- name: restart coredns
  kubernetes.core.k8s:
    kind: Deployment
    namespace: kube-system
    name: coredns
    state: present
    definition:
      spec:
        template:
          metadata:
            annotations:
              coredns-reload-trigger: "{{ lookup('pipe', 'date +%s') }}"
  delegate_to: localhost
