name: Ansible Playbook Check

on:
  push:
    paths:
      - 'ansible/**'
  pull_request:
    paths:
      - 'ansible/**'

jobs:
  ansible-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Check Ansible playbook syntax
      run: |
        ansible-playbook -i inventories/k3s.yml playbooks/k3s.yml --syntax-check

    - name: Run Ansible playbook in check mode
      run: |
        ansible-playbook -i inventories/k3s.yml playbooks/k3s.yml --check 