---
name: Runner Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      - kubernetes
      - self-hosted
      - shared-runners

    steps:
      - run: |
          echo "Runner funcionando!"
          uname -a
          hostname
