---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: wildcard-tls
  commonName: "*.homelab.tech"
  dnsNames:
    - "*.homelab.tech"
    - homelab.tech
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer

