---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-tls-ca-secret
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vault-tls-ca-secret
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: prod/infra/vault
        property: certificate
